name: ci

on:
  push:
    branches:
      - master
      - development
    tags:
      - '**'
  pull_request: { }

jobs:
  run-tests:
    name: "test ${{ matrix.os }} ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements/main.txt -r requirements/test.txt

      - name: Make coverage directory
        run: mkdir coverage

      - name: Test with coverage
        run: coverage run -m pytest tests
        env:
          COVERAGE_FILE: coverage/.coverage.${{ matrix.os }}.${{ matrix.python-version }}
          CONTEXT: ${{ matrix.os }}-py${{ matrix.python-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  build:
    needs: run-tests
    name: build distribution package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: |
          python -m pip install -U pip
          pip install build
      - name: build the binary wheel and source tarball
        run: python3 -m build
      - name: store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: waster
          path: dist/

#  release:
#    needs: coverage-combine
#    if: needs.test.outputs.result == 'success' && startsWith(github.ref, 'refs/tags/') &&
#    runs-on: ubuntu-latest
#    environment: release
#
#    permissions:
#      id-token: write
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.12'
#
#      - name: Install
#        run: pip install -U build
#
#      - name: Build
#        run: python -m build
#
#      - name: Upload package to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_TOKEN }}